### ISSUE TITLE
Doesn't work on 1.16.4

### ISSUE THREAD

**Issue by dom1s** [alexsatellite/HeadHunter#28]
Hello. I uploaded this plugin on 1.16.4 server and it doesn't work.

**Comment by dom1s** [comment]
![image](https://user-images.githubusercontent.com/50181423/100886582-ae6ff180-34bc-11eb-9813-ac9dd732ff7e.png)
Thats the console when I'm trying to load it.

**Comment by dom1s** [comment]
Managed to get it work, but now when I do headhunter rankup I get this:
![image](https://user-images.githubusercontent.com/50181423/100887845-183ccb00-34be-11eb-96e1-2b764be0141f.png)

**Comment by alexsatellite** [comment]
Hello, do you have a economy plugin on your server like EssentialsX?

The issue about the NBT API is now fixed and available in spigot.org

**Comment by dom1s** [comment]
I do have Essentials and Vault. Helix also. After the latest update I get this error and still doesn't work:
![image](https://user-images.githubusercontent.com/50181423/101262885-6e25a300-374a-11eb-8d2a-7aed7ad52a12.png)

**Comment by alexsatellite** [comment]
That error is because your java is outdated, try to update it to atleast java 15. Im still thinking to downgrade it tho as many users still have their servers with java 8.

**Comment by dom1s** [comment]
Would be nice to get it on java 11. Would be perfect.

**Comment by alexsatellite** [comment]
You can download it complied with java 11 now in Spigot.org
