### ISSUE TITLE
java 11

### ISSUE THREAD

**Issue by Goldenboy555** [alexsatellite/HeadHunter#30]
Hello,
Is it possible to get Headhunter rpg on java 11? I can also pay an extra money for it, because i really need it asap.

Have a nice day

**Comment by alexsatellite** [comment]
Hello, I updated the plugin to java 11. Available to download in spigot.

**Comment by Goldenboy555** [comment]
Hi, but i still get this error message:

[13:56:47 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'hh' in
me.ByteMagic.Helix.command.BukkitBCommand(hh)
        at
org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:182)
~[patched_1.16.4.jar:git-Purpur-918]
        at
org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2061)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1864)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1817)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
~[patched_1.16.4.jar:git-Purpur-918]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
~[patched_1.16.4.jar:git-Purpur-918]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1207)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1200)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1176)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1020)
~[patched_1.16.4.jar:git-Purpur-918]
        at
net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:180)
~[patched_1.16.4.jar:git-Purpur-918]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at
me.ByteMagic.HeadHunter.managers.GUI.HeadGUI.updateMenu(HeadGUI.java:132)
~[?:?]
        at
me.ByteMagic.HeadHunter.commands.HeadHunterCMD.perform(HeadHunterCMD.java:54)
~[?:?]
        at me.ByteMagic.Helix.command.BCommand.execute(BCommand.java:607)
~[?:?]
        at
me.ByteMagic.Helix.command.BukkitBCommand.execute(BukkitBCommand.java:47)
~[?:?]
        at
org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
~[patched_1.16.4.jar:git-Purpur-918]
        ... 18 more


This plugin is not available on 1.16.1? Must be 1.16.4?

2020-12-19, št, 21:39 ByteMagic <notifications@github.com> rašė:
